AWSTemplateFormatVersion: "2010-09-09"

Description:
  NAT Gateway tempalte


Parameters:
  ExportVPCStackName: 
    Description: "Name of the stack that exports values"
    Type: String
    Default: vpc
  

Resources:

  NatGateway1ElasticIP: 
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      Tags: 
        - Key: Name
          Value: EIP1

  NatGateway2ElasticIP: 
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      Tags: 
        - Key: Name
          Value: EIP2

  NatGateway1: 
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt NatGateway1ElasticIP.AllocationId
      ConnectivityType: public
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PublicSubnet1 
      Tags:
        - Key: Key 
          Value: NatGateway PublicSubnet1 

  NatGateway2: 
    Type: AWS::EC2::NatGateway 
    Properties: 
      AllocationId: !GetAtt NatGateway2ElasticIP.AllocationId 
      ConnectivityType: public
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PublicSubnet2 
      Tags: 
        - Key: Key 
          Value: NatGateway PublicSubnet2 

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-VPC 
      Tags: 
        - Key: Name
          Value: PrivateRouteTable1

  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      NatGatewayId: !Ref NatGateway1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PrivateSubnet1 

  PrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PrivateSubnet3

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-VPC 
      Tags: 
        - Key: Name
          Value: PrivateRouteTable2

  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      NatGatewayId: !Ref NatGateway2
      RouteTableId: !Ref PrivateRouteTable2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable2 
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PrivateSubnet2 

  PrivateSubnet4RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties: 
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: 
        Fn::ImportValue: !Sub ${ExportVPCStackName}-PrivateSubnet4 
